{"version":3,"file":"static/chunks/pages/_error-3260d80922554d34c6cd.js","mappings":"iGAAA,SAASA,EAAmBC,EAAKC,EAASC,EAAQC,EAAOC,EAAQC,EAAKC,GACpE,IACE,IAAIC,EAAOP,EAAIK,GAAKC,GAChBE,EAAQD,EAAKC,MACjB,MAAOC,GAEP,YADAP,EAAOO,GAILF,EAAKG,KACPT,EAAQO,GAERG,QAAQV,QAAQO,GAAOI,KAAKT,EAAOC,G,iGCRjCS,EAAU,SAAC,GAA+C,IAA7CC,EAA6C,EAA7CA,WAAYC,EAAiC,EAAjCA,sBAAuBC,EAAU,EAAVA,IASpD,OARKD,GAAyBC,GAI5BC,EAAAA,GAAwBD,IAInB,SAAC,UAAD,CAAoBF,WAAYA,KAGzCD,EAAQK,gBAAR,eDA0CC,ECA1C,GDA0CA,ECA1C,UAA0B,kGAASC,EAAT,EAASA,IAAKJ,EAAd,EAAcA,IAAKK,EAAnB,EAAmBA,OAAnB,SACQC,EAAAA,QAAAA,gBAAmC,CACjEF,IAAAA,EACAJ,IAAAA,IAHsB,WAClBO,EADkB,QAQNR,uBAAwB,GAetCC,EAvBoB,wBAwBtBC,EAAAA,GAAwBD,GAxBF,SA4BhBC,EAAAA,GAAa,KA5BG,gCA8BfM,GA9Be,eAoCxBN,EAAAA,GACE,IAAIO,MAAJ,0DAA6DH,KArCvC,UAuClBJ,EAAAA,GAAa,KAvCK,iCAyCjBM,GAzCiB,2CDCjB,WACL,IAAIE,EAAOC,KACPC,EAAOC,UACX,OAAO,IAAIjB,SAAQ,SAAUV,EAASC,GACpC,IAAIF,EAAMmB,EAAGU,MAAMJ,EAAME,GAEzB,SAASxB,EAAMK,GACbT,EAAmBC,EAAKC,EAASC,EAAQC,EAAOC,EAAQ,OAAQI,GAGlE,SAASJ,EAAOY,GACdjB,EAAmBC,EAAKC,EAASC,EAAQC,EAAOC,EAAQ,QAASY,GAGnEb,OAAM2B,QCfZ,sDA4CA,S,qBC3DKC,OAAOC,SAAWD,OAAOC,UAAY,IAAIC,KAAK,CAC7C,UACA,WACE,OAAO,EAAQ,U,qBCJvBC,EAAOC,QAAU,EAAjB,Q","sources":["webpack://_N_E/./node_modules/next/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js","webpack://_N_E/./pages/_error.jsx","webpack://_N_E/?fccd","webpack://_N_E/./node_modules/next/error.js"],"sourcesContent":["function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {\n  try {\n    var info = gen[key](arg);\n    var value = info.value;\n  } catch (error) {\n    reject(error);\n    return;\n  }\n\n  if (info.done) {\n    resolve(value);\n  } else {\n    Promise.resolve(value).then(_next, _throw);\n  }\n}\n\nexport default function _asyncToGenerator(fn) {\n  return function () {\n    var self = this,\n        args = arguments;\n    return new Promise(function (resolve, reject) {\n      var gen = fn.apply(self, args);\n\n      function _next(value) {\n        asyncGeneratorStep(gen, resolve, reject, _next, _throw, \"next\", value);\n      }\n\n      function _throw(err) {\n        asyncGeneratorStep(gen, resolve, reject, _next, _throw, \"throw\", err);\n      }\n\n      _next(undefined);\n    });\n  };\n}","import NextErrorComponent from \"next/error\";\n\nimport * as Sentry from \"@sentry/nextjs\";\n\nconst MyError = ({ statusCode, hasGetInitialPropsRun, err }) => {\n  if (!hasGetInitialPropsRun && err) {\n    // getInitialProps is not called in case of\n    // https://github.com/vercel/next.js/issues/8592. As a workaround, we pass\n    // err via _app.js so it can be captured\n    Sentry.captureException(err);\n    // Flushing is not required in this case as it only happens on the client\n  }\n\n  return <NextErrorComponent statusCode={statusCode} />;\n};\n\nMyError.getInitialProps = async ({ res, err, asPath }) => {\n  const errorInitialProps = await NextErrorComponent.getInitialProps({\n    res,\n    err,\n  });\n\n  // Workaround for https://github.com/vercel/next.js/issues/8592, mark when\n  // getInitialProps has run\n  errorInitialProps.hasGetInitialPropsRun = true;\n\n  // Running on the server, the response object (`res`) is available.\n  //\n  // Next.js will pass an err on the server if a page's data fetching methods\n  // threw or returned a Promise that rejected\n  //\n  // Running on the client (browser), Next.js will provide an err if:\n  //\n  //  - a page's `getInitialProps` threw or returned a Promise that rejected\n  //  - an exception was thrown somewhere in the React lifecycle (render,\n  //    componentDidMount, etc) that was caught by Next.js's React Error\n  //    Boundary. Read more about what types of exceptions are caught by Error\n  //    Boundaries: https://reactjs.org/docs/error-boundaries.html\n\n  if (err) {\n    Sentry.captureException(err);\n\n    // Flushing before returning is necessary if deploying to Vercel, see\n    // https://vercel.com/docs/platform/limits#streaming-responses\n    await Sentry.flush(2000);\n\n    return errorInitialProps;\n  }\n\n  // If this point is reached, getInitialProps was called without any\n  // information about what the error might be. This is unexpected and may\n  // indicate a bug introduced in Next.js, so record it in Sentry\n  Sentry.captureException(\n    new Error(`_error.js getInitialProps missing data at path: ${asPath}`)\n  );\n  await Sentry.flush(2000);\n\n  return errorInitialProps;\n};\n\nexport default MyError;\n","\n    (window.__NEXT_P = window.__NEXT_P || []).push([\n      \"/_error\",\n      function () {\n        return require(\"private-next-pages/_error.jsx\");\n      }\n    ]);\n  ","module.exports = require('./dist/pages/_error')\n"],"names":["asyncGeneratorStep","gen","resolve","reject","_next","_throw","key","arg","info","value","error","done","Promise","then","MyError","statusCode","hasGetInitialPropsRun","err","Sentry","getInitialProps","fn","res","asPath","NextErrorComponent","errorInitialProps","Error","self","this","args","arguments","apply","undefined","window","__NEXT_P","push","module","exports"],"sourceRoot":""}